### Q1. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [3]:
import numpy as np

give_list = [1,2,3,4,5,6,99]
print("Given list is: {}".format(give_list))

list_to_arr = np.array(give_list)
print("Give list to one-dimensional NumPy array is: {}".format(list_to_arr))

Given list is: [1, 2, 3, 4, 5, 6, 99]
Give list to one-dimensional NumPy array is: [ 1  2  3  4  5  6 99]


---

### Q2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [23]:
import numpy as np

arr1 = np.arange(2,11)
print("Give array with values ranging from 2 to 10 is: {}".format(arr1))
print("\n3x3 Matrix is: \n{}".format(arr1.reshape(3,3)))


Give array with values ranging from 2 to 10 is: [ 2  3  4  5  6  7  8  9 10]

3x3 Matrix is: 
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


---

### Q3. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [30]:
import numpy as np

arr_with_zero = np.zeros(10)
print("Array with 10 Null values is: {}".format(arr_with_zero))

arr_with_zero[5] = 11
print("Updated array is: {}".format(arr_with_zero))

Array with 10 Null values is: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated array is: [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


---

### Q4. Write a NumPy program to create an array with values ranging from 12 to 38.

In [34]:
import numpy as np

arr1 = np.arange(12,39)
print("Array with values ranging from 12 to 38 is: {}".format(arr1))

Array with values ranging from 12 to 38 is: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


---

### Q5. Write a NumPy program to reverse an array (first element becomes last).

In [36]:
import numpy as np

arr1 = np.arange(1,98,5)
print("Give array is: {}".format(arr1))

rev_arr1 = arr1[::-1]
print("Reverse of 'arr1' is: {}".format(rev_arr1))

Give array is: [ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
Reverse of 'arr1' is: [96 91 86 81 76 71 66 61 56 51 46 41 36 31 26 21 16 11  6  1]


---

### Q6. Write a NumPy program to convert an array to a float type.

In [38]:
import numpy as np

arr1 = np.arange(12,54,4)
print("Given array is: {}".format(arr1))

arr2 = np.asfarray(arr1)
print("Converted 'arr1' to float type is: {}".format(arr2))

Given array is: [12 16 20 24 28 32 36 40 44 48 52]
Converted 'arr1' to float type is: [12. 16. 20. 24. 28. 32. 36. 40. 44. 48. 52.]


---

### Q7. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [45]:
import numpy as np

arr1 = np.ones((6,6))
print("Original array is:\n{}".format(arr1))
arr1[1:-1,1:-1] = 0
print("\n1 on the border and 0 inside in the array:\n{}".format(arr1))

Original array is:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array:
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


---

### Q8. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [54]:
import numpy as np

arr1 = np.ones((3,3))
print("Original array is:\n{}".format(arr1))
arr1 = np.pad(arr1, pad_width=1, mode='constant', constant_values=0)
print("\n0 on the border and 1 inside in the array:\n{}".format(arr1))

Original array is:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

0 on the border and 1 inside in the array:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


---

### Q9. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [58]:
import numpy as np

arr1 = np.ones((3,3))
arr1 = np.zeros((8,8),dtype=int)
arr1[1::2,::2] = 1
arr1[::2,1::2] = 1
print("Checkerboard pattern:\n{}".format(arr1))

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


---

### Q10. Write a NumPy program to convert a list and tuple into arrays.

In [61]:
import numpy as np
given_list = [x for x in range(0,12,3)]
given_tuple = ([1,2],[4,5])

print("Given List is: {}\nGiven Tuple is: {}\n".format(given_list,given_tuple))
print("List to array is: {}\nTuple to Array is:\n{}".format(np.asarray(given_list),np.asarray(given_tuple)))

Given List is: [0, 3, 6, 9]
Given Tuple is: ([1, 2], [4, 5])

List to array is: [0 3 6 9]
Tuple to Array is:
[[1 2]
 [4 5]]


---

### Q11. Write a NumPy program to append values to the end of an array.

In [66]:
import numpy as np

arr1 = np.array([1,2,3])
print("Original Array is: {}".format(arr1))

arr1 = np.append(arr1,[[20,30],[999,122]])
print("Updated Array is: {}".format(arr1))

Original Array is: [1 2 3]
Updated Array is: [  1   2   3  20  30 999 122]


---

### Q12. Write a NumPy program to create an empty and a full array.

In [70]:
import numpy as np

empty_arr = np.empty((2,4))
print("Empty array is: {}".format(empty_arr))

full_arr = np.full((3,4),5)
print("\nFull array is:\n{}".format(full_arr))

Empty array is: [[0.000e+000 0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 7.075e-321 0.000e+000 0.000e+000]]

Full array is:
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


---

### Q13. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

In [81]:
import numpy as np

centi_arr = np.array([0, 62.1, 7.3, 95, 37.7])
print("Centigrade Values are: {}".format(centi_arr))
print("Centigrade to Fahrenheit Values are: {}".format(centi_arr*1.8+32))

Centigrade Values are: [ 0.  62.1  7.3 95.  37.7]
Centigrade to Fahrenheit Values are: [ 32.   143.78  45.14 203.    99.86]


---

### Q14. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.

In [87]:
import numpy as np

arr1 = np.sqrt([1+0j])
arr2 = np.sqrt([0+1j])
print("Original array-1: {}".format(x))
print("Original array-2: {}".format(y))
print("\nReal part of the array:")
print(arr1.real)
print(arr2.real)
print("\nImaginary part of the array:")
print(arr1.imag)
print(arr2.imag)

Original array-1: [1.+0.j]
Original array-2: [0.70710678+0.70710678j]

Real part of the array:
[1.]
[0.70710678]

Imaginary part of the array:
[0.]
[0.70710678]


---