## Multiple Linear Regression

### Case-Study (CS-29)

---

### Importing libraries and loading data

In [22]:
import numpy as np 
import pandas as pd

In [23]:
df = pd.read_excel("datasets/Health_score.xlsx")
df

Birth Rate   No of Hospitlas   No of Doctors   Annual Income   \
0           8.0                78             284             9.1   
1           9.3                68             433             8.7   
2           7.5                70             739             7.2   
3           8.9                96            1792             8.9   
4          10.2                74             477             8.3   
5           8.3               111             362            10.9   
6           8.8                77             671            10.0   
7           8.8               168             636             9.1   
8          10.7                82             329             8.7   
9          11.7                89             634             7.6   
10          8.5               149             631            10.8   
11          8.3                60             257             9.5   
12          8.2                96             284             8.8   
13          7.9                83             603             9.5   
14         10.3               130             686             8.7   
15          7.4               145             345            11.2   
16          9.6               112            1357             9.7   
17          9.3               131             544             9.6   
18         10.6                80             205             9.1   
19          9.7               130            1264             9.2   
20         11.6               140             688             8.3   
21          8.1               154             354             8.4   
22          9.8               118            1632             9.4   
23          7.4                94             348             9.8   
24          9.4               119             370            10.4   
25         11.2               153             648             9.9   
26          9.1               116             366             9.2   
27         10.5                97             540            10.3   
28         11.9               176             680             8.9   
29          8.4                75             345             9.6   
30          5.0               134             525            10.3   
31          9.8               161             870            10.4   
32          9.8               111             669             9.7   
33         10.8               114             452             9.6   
34         10.1               142             430            10.7   
35         10.9               238             822            10.3   
36          9.2                78             190            10.7   
37          8.3               196             867             9.6   
38          7.3               125             969            10.5   
39          9.4                82             499             7.7   
40          9.4               125             925            10.2   
41          9.8               129             353             9.9   
42          3.6                84             288             8.4   
43          8.4               183             718            10.4   
44         10.8               119             540             9.2   
45         10.1               180             668            13.0   
46          9.0                82             347             8.8   
47         10.0                71             345             9.2   
48         11.3               118             463             7.8   
49         11.3               121             728             8.2   
50         12.8                68             383             7.4   
51         10.0               112             316            10.4   
52          6.7               109             388             8.9   

    Population Density   
0                   109  
1                   144  
2                   113  
3                    97  
4                   206  
5                   124  
6                   152  
7                   162  
8                   150  
9                

### Creating x and y variable

In [24]:
x = df.iloc[:,1:]
x.head()

No of Hospitlas   No of Doctors   Annual Income   Population Density 
0                78             284             9.1                  109
1                68             433             8.7                  144
2                70             739             7.2                  113
3                96            1792             8.9                   97
4                74             477             8.3                  206

In [25]:
y = df.iloc[:,0]
y.head()

0     8.0
1     9.3
2     7.5
3     8.9
4    10.2
Name: Birth Rate , dtype: float64

### Creating Train-Test split

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)
print(y_test)

30     5.0
2      7.5
51    10.0
32     9.8
31     9.8
46     9.0
34    10.1
39     9.4
45    10.1
19     9.7
10     8.5
3      8.9
21     8.1
49    11.3
38     7.3
41     9.8
Name: Birth Rate , dtype: float64


### Creating LinearRegression model

In [27]:
from sklearn.linear_model import LinearRegression
regressor =  LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

### Predictions

In [28]:
y_pred = regressor.predict (X_test )
y_pred

array([ 8.70113834, 10.89481779,  9.04497486,  9.73713255,  9.39764635,
       10.20037156,  8.96247615, 10.50326655,  7.53302753,  9.77926718,
        6.71761952, 11.44699294, 10.05620668, 10.73411527,  8.71336989,
        9.54444788])

In [29]:
y_test

30     5.0
2      7.5
51    10.0
32     9.8
31     9.8
46     9.0
34    10.1
39     9.4
45    10.1
19     9.7
10     8.5
3      8.9
21     8.1
49    11.3
38     7.3
41     9.8
Name: Birth Rate , dtype: float64

### Prediction of full dataset

In [30]:
y_pred = regressor.predict(x)
y_pred

array([ 9.13424356,  9.15921784, 10.89481779, 11.44699294,  8.80913599,
        8.02539168,  8.56835611,  9.36490771,  9.01222504, 10.33756342,
        6.71761952,  8.77627172,  9.38032601,  8.49468483,  9.90783308,
        7.56375939,  9.42370781,  8.60110048,  8.83754416,  9.77926718,
       10.75991319, 10.05620668, 10.95449756,  8.73564291,  8.79727097,
        9.73676118,  9.40749357,  8.91851954, 10.5022547 ,  9.06546361,
        8.70113834,  9.39764635,  9.73713255,  9.72034985,  8.96247615,
        9.95591465,  8.14457662, 10.07962044,  8.71336989, 10.50326655,
        9.6455954 ,  9.54444788,  9.6098182 ,  9.72310704, 10.15064717,
        7.53302753, 10.20037156,  9.78032521, 11.20648005, 10.73411527,
       10.91586796,  9.04497486,  9.69361191])

In [31]:
y

0      8.0
1      9.3
2      7.5
3      8.9
4     10.2
5      8.3
6      8.8
7      8.8
8     10.7
9     11.7
10     8.5
11     8.3
12     8.2
13     7.9
14    10.3
15     7.4
16     9.6
17     9.3
18    10.6
19     9.7
20    11.6
21     8.1
22     9.8
23     7.4
24     9.4
25    11.2
26     9.1
27    10.5
28    11.9
29     8.4
30     5.0
31     9.8
32     9.8
33    10.8
34    10.1
35    10.9
36     9.2
37     8.3
38     7.3
39     9.4
40     9.4
41     9.8
42     3.6
43     8.4
44    10.8
45    10.1
46     9.0
47    10.0
48    11.3
49    11.3
50    12.8
51    10.0
52     6.7
Name: Birth Rate , dtype: float64

### Concatenating the Predictions with Actual

In [32]:
y_pred = pd.DataFrame(y_pred,columns= ['Prediction'])
final = pd.concat([df, y_pred], axis =1)
final

Birth Rate   No of Hospitlas   No of Doctors   Annual Income   \
0           8.0                78             284             9.1   
1           9.3                68             433             8.7   
2           7.5                70             739             7.2   
3           8.9                96            1792             8.9   
4          10.2                74             477             8.3   
5           8.3               111             362            10.9   
6           8.8                77             671            10.0   
7           8.8               168             636             9.1   
8          10.7                82             329             8.7   
9          11.7                89             634             7.6   
10          8.5               149             631            10.8   
11          8.3                60             257             9.5   
12          8.2                96             284             8.8   
13          7.9                83             603             9.5   
14         10.3               130             686             8.7   
15          7.4               145             345            11.2   
16          9.6               112            1357             9.7   
17          9.3               131             544             9.6   
18         10.6                80             205             9.1   
19          9.7               130            1264             9.2   
20         11.6               140             688             8.3   
21          8.1               154             354             8.4   
22          9.8               118            1632             9.4   
23          7.4                94             348             9.8   
24          9.4               119             370            10.4   
25         11.2               153             648             9.9   
26          9.1               116             366             9.2   
27         10.5                97             540            10.3   
28         11.9               176             680             8.9   
29          8.4                75             345             9.6   
30          5.0               134             525            10.3   
31          9.8               161             870            10.4   
32          9.8               111             669             9.7   
33         10.8               114             452             9.6   
34         10.1               142             430            10.7   
35         10.9               238             822            10.3   
36          9.2                78             190            10.7   
37          8.3               196             867             9.6   
38          7.3               125             969            10.5   
39          9.4                82             499             7.7   
40          9.4               125             925            10.2   
41          9.8               129             353             9.9   
42          3.6                84             288             8.4   
43          8.4               183             718            10.4   
44         10.8               119             540             9.2   
45         10.1               180             668            13.0   
46          9.0                82             347             8.8   
47         10.0                71             345             9.2   
48         11.3               118             463             7.8   
49         11.3               121             728             8.2   
50         12.8                68             383             7.4   
51         10.0               112             316            10.4   
52          6.7               109             388             8.9   

    Population Density   Prediction  
0                   109    9.134244  
1                   144    9.159218  
2                   113   10.894818  
3                    97   11.446993  
4                   206    8.809136  
5                   124    8.025392  
6          

### Coeffecient and Intercept

In [33]:
regressor.coef_

array([ 0.00402374,  0.00130999, -0.6533895 , -0.01118096])

In [34]:
regressor.intercept_

15.61292257001471

### Accuracy with OLS

In [35]:
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog = x)
reg_ols = reg_ols.fit()
print (reg_ols.summary())

                                 OLS Regression Results                                
Dep. Variable:            Birth Rate    R-squared (uncentered):                   0.954
Model:                            OLS   Adj. R-squared (uncentered):              0.950
Method:                 Least Squares   F-statistic:                              254.2
Date:                Sat, 28 May 2022   Prob (F-statistic):                    4.15e-32
Time:                        11:44:25   Log-Likelihood:                         -112.63
No. Observations:                  53   AIC:                                      233.3
Df Residuals:                      49   BIC:                                      241.1
Df Model:                           4                                                  
Covariance Type:            nonrobust                                                  
                          coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------

---