## Supervised Learning 
### Case Study - 6 (CS 35)

**Objective:**


Employ SVM from scikit learn for binary classification.

Impact of preprocessing data and hyper paramter search using grid search and random search CV .

**Questions:**


1. Load the data from “college.csv” that has attributes collected about private and public colleges for a particular year. We will try to predict the private/public status of the college from other attributes.


2. Use LabelEncoder to encode the target variable in to numerical form and split the data such that 20% of the data is set aside for testing.

    
3. Fit a linear svm from scikit learn and observe the accuracy. [Hint: Use Linear SVC]



4. Preprocess the data using StandardScalar and fit the same model again and observe the change in accuracy.[Hint: Refer to scikitlearn’s preprocessing methods]



5. Use scikit learn’s gridsearch and Random Search CV to select the best hyperparameter for a non-linear SVM, identify the model with best score and its parameters.[Hint: Refer to model_selection module of Scikit learn]

### Importing libraries and loading data

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("datasets/College.csv")
df

Private   Apps  Accept  Enroll  Top10perc  Top25perc  F.Undergrad  \
0       Yes   1660    1232     721         23         52         2885   
1       Yes   2186    1924     512         16         29         2683   
2       Yes   1428    1097     336         22         50         1036   
3       Yes    417     349     137         60         89          510   
4       Yes    193     146      55         16         44          249   
..      ...    ...     ...     ...        ...        ...          ...   
772      No   2197    1515     543          4         26         3089   
773     Yes   1959    1805     695         24         47         2849   
774     Yes   2097    1915     695         34         61         2793   
775     Yes  10705    2453    1317         95         99         5217   
776     Yes   2989    1855     691         28         63         2988   

     P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  Terminal  \
0            537      7440        3300    450      2200   70        78   
1           1227     12280        6450    750      1500   29        30   
2             99     11250        3750    400      1165   53        66   
3             63     12960        5450    450       875   92        97   
4            869      7560        4120    800      1500   76        72   
..           ...       ...         ...    ...       ...  ...       ...   
772         2029      6797        3900    500      1200   60        60   
773         1107     11520        4960    600      1250   73        75   
774          166      6900        4200    617       781   67        75   
775           83     19840        6510    630      2115   96        96   
776         1726      4990        3560    500      1250   75        75   

     S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0         18.1           12    7041         60  
1         12.2           16   10527         56  
2         12.9           30    8735         54  
3          7.7           37   19016         59  
4         11.9            2   10922         15  
..         ...          ...     ...        ...  
772       21.0           14    4469         40  
773       13.3           31    9189         83  
774       14.4           20    8323         49  
775        5.8           49   40386         99  
776       18.1           28    4509         99  

[777 rows x 18 columns]

In [4]:
df.shape

(777, 18)

In [5]:
df.columns

Index(['Private', 'Apps', 'Accept', 'Enroll', 'Top10perc', 'Top25perc',
       'F.Undergrad', 'P.Undergrad', 'Outstate', 'Room.Board', 'Books',
       'Personal', 'PhD', 'Terminal', 'S.F.Ratio', 'perc.alumni', 'Expend',
       'Grad.Rate'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Private      777 non-null    object 
 1   Apps         777 non-null    int64  
 2   Accept       777 non-null    int64  
 3   Enroll       777 non-null    int64  
 4   Top10perc    777 non-null    int64  
 5   Top25perc    777 non-null    int64  
 6   F.Undergrad  777 non-null    int64  
 7   P.Undergrad  777 non-null    int64  
 8   Outstate     777 non-null    int64  
 9   Room.Board   777 non-null    int64  
 10  Books        777 non-null    int64  
 11  Personal     777 non-null    int64  
 12  PhD          777 non-null    int64  
 13  Terminal     777 non-null    int64  
 14  S.F.Ratio    777 non-null    float64
 15  perc.alumni  777 non-null    int64  
 16  Expend       777 non-null    int64  
 17  Grad.Rate    777 non-null    int64  
dtypes: float64(1), int64(16), object(1)
memory usage: 

In [7]:
df.describe()

Apps        Accept       Enroll   Top10perc   Top25perc  \
count    777.000000    777.000000   777.000000  777.000000  777.000000   
mean    3001.638353   2018.804376   779.972973   27.558559   55.796654   
std     3870.201484   2451.113971   929.176190   17.640364   19.804778   
min       81.000000     72.000000    35.000000    1.000000    9.000000   
25%      776.000000    604.000000   242.000000   15.000000   41.000000   
50%     1558.000000   1110.000000   434.000000   23.000000   54.000000   
75%     3624.000000   2424.000000   902.000000   35.000000   69.000000   
max    48094.000000  26330.000000  6392.000000   96.000000  100.000000   

        F.Undergrad   P.Undergrad      Outstate   Room.Board        Books  \
count    777.000000    777.000000    777.000000   777.000000   777.000000   
mean    3699.907336    855.298584  10440.669241  4357.526384   549.380952   
std     4850.420531   1522.431887   4023.016484  1096.696416   165.105360   
min      139.000000      1.000000   2340.000000  1780.000000    96.000000   
25%      992.000000     95.000000   7320.000000  3597.000000   470.000000   
50%     1707.000000    353.000000   9990.000000  4200.000000   500.000000   
75%     4005.000000    967.000000  12925.000000  5050.000000   600.000000   
max    31643.000000  21836.000000  21700.000000  8124.000000  2340.000000   

          Personal         PhD    Terminal   S.F.Ratio  perc.alumni  \
count   777.000000  777.000000  777.000000  777.000000   777.000000   
mean   1340.642214   72.660232   79.702703   14.089704    22.743887   
std     677.071454   16.328155   14.722359    3.958349    12.391801   
min     250.000000    8.000000   24.000000    2.500000     0.000000   
25%     850.000000   62.000000   71.000000   11.500000    13.000000   
50%    1200.000000   75.000000   82.000000   13.600000    21.000000   
75%    1700.000000   85.000000   92.000000   16.500000    31.000000   
max    6800.000000  103.000000  100.000000   39.800000    64.000000   

             Expend  Grad.Rate  
count    777.000000  777.00000  
mean    9660.171171   65.46332  
std     5221.768440   17.17771  
min     3186.000000   10.00000  
25%     6751.000000   53.00000  
50%     8377.000000   65.00000  
75%    10830.000000   78.00000  
max    56233.000000  118.00000

---

### Train-Test Split

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [9]:
x = df.iloc[:,1:].values

In [10]:
y = df.iloc[:,0].values

### Label Encoding

In [11]:
target_encoder = LabelEncoder()

y = target_encoder.fit_transform(y)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=1)

print("X_train shape: {}".format(X_train.shape))

X_train shape: (582, 17)


### Linear SVC Model

In [13]:
from sklearn.svm import LinearSVC, SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

model = LinearSVC()

model.fit(X_train, y_train)

C:\Users\sahil\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC()

### Predictions

In [14]:
y_pred = model.predict(X_test)
print("Predictions are:\n{}".format(y_pred))

Predictions are:
[0 1 0 0 0 1 1 1 1 1 0 1 0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 1 0 1 0 1 1 1 1 1 0
 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 1 1 0 1 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 1
 0 0 0 1 0 0 0 1 1 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 1
 0 1 0 1 1 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0 0 1 0 1 0 1 1
 0 0 1 0 1 1 1 0 1 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 0
 1 0 0 0 1 1 0 1 0 0]


### Confusion Matrix

In [15]:
print("Confusion Matrix:\n{}".format(confusion_matrix(y_pred, y_test)))

Confusion Matrix:
[[51 47]
 [ 0 97]]


### Accuracy Score

In [16]:
print("Accuracy Score is: {}".format(accuracy_score(y_pred, y_test)))

Accuracy Score is: 0.7589743589743589


### Classification Reports

In [17]:
print("Classification reports:\n{}".format(classification_report(y_pred, y_test)))

Classification reports:
              precision    recall  f1-score   support

           0       1.00      0.52      0.68        98
           1       0.67      1.00      0.80        97

    accuracy                           0.76       195
   macro avg       0.84      0.76      0.74       195
weighted avg       0.84      0.76      0.74       195



---

### SVC model with Kernel = Linear

In [18]:
model2 = SVC(kernel='linear')
model2.fit(X_train, y_train)

SVC(kernel='linear')

### Confusion Matrix

In [19]:
print("Confusion matrix:\n{}".format(confusion_matrix(y_pred, y_test)))

Confusion matrix:
[[51 47]
 [ 0 97]]


### Accuracy Score

In [20]:
print("Accuracy Score: {}".format(accuracy_score(y_pred, y_test)))

Accuracy Score: 0.7589743589743589


### Classification Reports

In [21]:
print("Classification report:\n{}".format(classification_report(y_pred, y_test)))

Classification report:
              precision    recall  f1-score   support

           0       1.00      0.52      0.68        98
           1       0.67      1.00      0.80        97

    accuracy                           0.76       195
   macro avg       0.84      0.76      0.74       195
weighted avg       0.84      0.76      0.74       195



---

### SVC model with kernel = rbf

In [22]:
model3 = SVC(kernel='rbf')
model3.fit(X_train, y_train)

SVC()

### Confusion Matrix

In [23]:
print("Confusion matrix:\n{}".format(confusion_matrix(y_pred, y_test)))

Confusion matrix:
[[51 47]
 [ 0 97]]


### Accuracy Score

In [24]:
print("Accuracy Score: {}".format(accuracy_score(y_pred, y_test)))

Accuracy Score: 0.7589743589743589


### Classification Reports

In [25]:
print("Classification report:\n{}".format(classification_report(y_pred, y_test)))

Classification report:
              precision    recall  f1-score   support

           0       1.00      0.52      0.68        98
           1       0.67      1.00      0.80        97

    accuracy                           0.76       195
   macro avg       0.84      0.76      0.74       195
weighted avg       0.84      0.76      0.74       195



---

### Importing GridSearchCV and RandomSearchCV with StandardScaler

In [39]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
import numpy as np

### Standardization of Data

In [32]:
scaler = StandardScaler()

X = df.iloc[:,1:].values
y = df.iloc[:,0].values

X = scaler.fit_transform(X)

### Label encoding

In [33]:
target_encoder = LabelEncoder()

y = target_encoder.fit_transform(y)

### Train-test split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

print("X_train shape = {}".format(X_train.shape))

X_train shape = (582, 17)


### SVC model with kernel = rbf

In [35]:
model4 = SVC(kernel='rbf')
model4.fit(X_train, y_train)

SVC()

### Confusion matrix

In [36]:
print("Confusion matrix:\n{}".format(confusion_matrix(y_pred, y_test)))

Confusion matrix:
[[51 47]
 [ 0 97]]


### Accuracy Score

In [37]:
print("Accuracy Score: {}".format(accuracy_score(y_pred, y_test)))

Accuracy Score: 0.7589743589743589


### Classification Reports

In [38]:
print("Classification report:\n{}".format(classification_report(y_pred, y_test)))

Classification report:
              precision    recall  f1-score   support

           0       1.00      0.52      0.68        98
           1       0.67      1.00      0.80        97

    accuracy                           0.76       195
   macro avg       0.84      0.76      0.74       195
weighted avg       0.84      0.76      0.74       195



---

### GridSearch CV model

In [42]:
C_range = np.logspace(-2, 10, 13)
gamma_range = np.logspace(-9, 3, 13)
param_grid = dict( gamma=gamma_range,C=C_range)
grid = GridSearchCV(SVC(), param_grid=param_grid,verbose=2)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 169 candidates, totalling 845 fits
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-07; total time=   0.0s
[CV] END ................................C=0.0

[CV] END ...................................C=0.1, gamma=1.0; total time=   0.0s
[CV] END ..................................C=0.1, gamma=10.0; total time=   0.0s
[CV] END ..................................C=0.1, gamma=10.0; total time=   0.0s
[CV] END ..................................C=0.1, gamma=10.0; total time=   0.0s
[CV] END ..................................C=0.1, gamma=10.0; total time=   0.0s
[CV] END ..................................C=0.1, gamma=10.0; total time=   0.0s
[CV] END .................................C=0.1, gamma=100.0; total time=   0.0s
[CV] END .................................C=0.1, gamma=100.0; total time=   0.0s
[CV] END .................................C=0.1, gamma=100.0; total time=   0.0s
[CV] END .................................C=0.1, gamma=100.0; total time=   0.0s
[CV] END .................................C=0.1, gamma=100.0; total time=   0.0s
[CV] END ................................C=0.1, gamma=1000.0; total time=   0.0s
[CV] END ...................

[CV] END ................................C=10.0, gamma=1e-05; total time=   0.0s
[CV] END ................................C=10.0, gamma=1e-05; total time=   0.0s
[CV] END ...............................C=10.0, gamma=0.0001; total time=   0.0s
[CV] END ...............................C=10.0, gamma=0.0001; total time=   0.0s
[CV] END ...............................C=10.0, gamma=0.0001; total time=   0.0s
[CV] END ...............................C=10.0, gamma=0.0001; total time=   0.0s
[CV] END ...............................C=10.0, gamma=0.0001; total time=   0.0s
[CV] END ................................C=10.0, gamma=0.001; total time=   0.0s
[CV] END ................................C=10.0, gamma=0.001; total time=   0.0s
[CV] END ................................C=10.0, gamma=0.001; total time=   0.0s
[CV] END ................................C=10.0, gamma=0.001; total time=   0.0s
[CV] END ................................C=10.0, gamma=0.001; total time=   0.0s
[CV] END ...................

[CV] END ..............................C=100.0, gamma=1000.0; total time=   0.0s
[CV] END ..............................C=100.0, gamma=1000.0; total time=   0.0s
[CV] END ..............................C=100.0, gamma=1000.0; total time=   0.0s
[CV] END ..............................C=1000.0, gamma=1e-09; total time=   0.0s
[CV] END ..............................C=1000.0, gamma=1e-09; total time=   0.0s
[CV] END ..............................C=1000.0, gamma=1e-09; total time=   0.0s
[CV] END ..............................C=1000.0, gamma=1e-09; total time=   0.0s
[CV] END ..............................C=1000.0, gamma=1e-09; total time=   0.0s
[CV] END ..............................C=1000.0, gamma=1e-08; total time=   0.0s
[CV] END ..............................C=1000.0, gamma=1e-08; total time=   0.0s
[CV] END ..............................C=1000.0, gamma=1e-08; total time=   0.0s
[CV] END ..............................C=1000.0, gamma=1e-08; total time=   0.0s
[CV] END ...................

[CV] END ...............................C=10000.0, gamma=1.0; total time=   0.0s
[CV] END ...............................C=10000.0, gamma=1.0; total time=   0.0s
[CV] END ..............................C=10000.0, gamma=10.0; total time=   0.0s
[CV] END ..............................C=10000.0, gamma=10.0; total time=   0.0s
[CV] END ..............................C=10000.0, gamma=10.0; total time=   0.0s
[CV] END ..............................C=10000.0, gamma=10.0; total time=   0.0s
[CV] END ..............................C=10000.0, gamma=10.0; total time=   0.0s
[CV] END .............................C=10000.0, gamma=100.0; total time=   0.0s
[CV] END .............................C=10000.0, gamma=100.0; total time=   0.0s
[CV] END .............................C=10000.0, gamma=100.0; total time=   0.0s
[CV] END .............................C=10000.0, gamma=100.0; total time=   0.0s
[CV] END .............................C=10000.0, gamma=100.0; total time=   0.0s
[CV] END ...................

[CV] END ...........................C=1000000.0, gamma=1e-05; total time=   0.0s
[CV] END ..........................C=1000000.0, gamma=0.0001; total time=   0.0s
[CV] END ..........................C=1000000.0, gamma=0.0001; total time=   0.0s
[CV] END ..........................C=1000000.0, gamma=0.0001; total time=   0.0s
[CV] END ..........................C=1000000.0, gamma=0.0001; total time=   0.1s
[CV] END ..........................C=1000000.0, gamma=0.0001; total time=   0.0s
[CV] END ...........................C=1000000.0, gamma=0.001; total time=   0.0s
[CV] END ...........................C=1000000.0, gamma=0.001; total time=   0.0s
[CV] END ...........................C=1000000.0, gamma=0.001; total time=   0.0s
[CV] END ...........................C=1000000.0, gamma=0.001; total time=   0.0s
[CV] END ...........................C=1000000.0, gamma=0.001; total time=   0.1s
[CV] END ............................C=1000000.0, gamma=0.01; total time=   0.0s
[CV] END ...................

[CV] END .........................C=100000000.0, gamma=1e-09; total time=   0.0s
[CV] END .........................C=100000000.0, gamma=1e-09; total time=   0.0s
[CV] END .........................C=100000000.0, gamma=1e-09; total time=   0.0s
[CV] END .........................C=100000000.0, gamma=1e-09; total time=   0.0s
[CV] END .........................C=100000000.0, gamma=1e-08; total time=   0.0s
[CV] END .........................C=100000000.0, gamma=1e-08; total time=   0.0s
[CV] END .........................C=100000000.0, gamma=1e-08; total time=   0.0s
[CV] END .........................C=100000000.0, gamma=1e-08; total time=   0.0s
[CV] END .........................C=100000000.0, gamma=1e-08; total time=   0.0s
[CV] END .........................C=100000000.0, gamma=1e-07; total time=   0.0s
[CV] END .........................C=100000000.0, gamma=1e-07; total time=   0.0s
[CV] END .........................C=100000000.0, gamma=1e-07; total time=   0.0s
[CV] END ...................

[CV] END .........................C=1000000000.0, gamma=10.0; total time=   0.0s
[CV] END .........................C=1000000000.0, gamma=10.0; total time=   0.0s
[CV] END .........................C=1000000000.0, gamma=10.0; total time=   0.0s
[CV] END .........................C=1000000000.0, gamma=10.0; total time=   0.0s
[CV] END .........................C=1000000000.0, gamma=10.0; total time=   0.0s
[CV] END ........................C=1000000000.0, gamma=100.0; total time=   0.0s
[CV] END ........................C=1000000000.0, gamma=100.0; total time=   0.0s
[CV] END ........................C=1000000000.0, gamma=100.0; total time=   0.0s
[CV] END ........................C=1000000000.0, gamma=100.0; total time=   0.0s
[CV] END ........................C=1000000000.0, gamma=100.0; total time=   0.0s
[CV] END .......................C=1000000000.0, gamma=1000.0; total time=   0.0s
[CV] END .......................C=1000000000.0, gamma=1000.0; total time=   0.0s
[CV] END ...................

### Best Parameter

In [41]:
print("Best parameter is {}, with score of {}".format(grid.best_params_, grid.best_score_))

Best parameter is {'C': 10.0, 'gamma': 0.01}, with score of 0.9415856174476863


### Predictions

In [43]:
y_pred = grid.predict(X_test)

### Confusion Matrix

In [44]:
print("Confusion matrix:\n{}".format(confusion_matrix(y_pred, y_test)))

Confusion matrix:
[[ 44   3]
 [  7 141]]


### Accuracy Score

In [45]:
print("Accuracy Score: {}".format(accuracy_score(y_pred, y_test)))

Accuracy Score: 0.9487179487179487


### Classification report

In [47]:
print("Classification report:\n{}".format(classification_report(y_pred, y_test)))

Classification report:
              precision    recall  f1-score   support

           0       0.86      0.94      0.90        47
           1       0.98      0.95      0.97       148

    accuracy                           0.95       195
   macro avg       0.92      0.94      0.93       195
weighted avg       0.95      0.95      0.95       195



---

### RandomSearch CV model

In [48]:
params = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001]}
print (params)
rgrid =  RandomizedSearchCV(SVC(), param_distributions=params, n_iter= 12,cv = 10,  verbose=2 )
rgrid.fit(X_train, y_train)

{'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001]}
Fitting 10 folds for each of 12 candidates, totalling 120 fits
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END ...................................C=1, gamma=0.001; total ti

[CV] END ......................................C=10, gamma=1; total time=   0.0s
[CV] END ......................................C=10, gamma=1; total time=   0.0s
[CV] END .....................................C=100, gamma=1; total time=   0.0s
[CV] END .....................................C=100, gamma=1; total time=   0.0s
[CV] END .....................................C=100, gamma=1; total time=   0.0s
[CV] END .....................................C=100, gamma=1; total time=   0.0s
[CV] END .....................................C=100, gamma=1; total time=   0.0s
[CV] END .....................................C=100, gamma=1; total time=   0.0s
[CV] END .....................................C=100, gamma=1; total time=   0.0s
[CV] END .....................................C=100, gamma=1; total time=   0.0s
[CV] END .....................................C=100, gamma=1; total time=   0.0s
[CV] END .....................................C=100, gamma=1; total time=   0.0s


RandomizedSearchCV(cv=10, estimator=SVC(), n_iter=12,
                   param_distributions={'C': [0.1, 1, 10, 100],
                                        'gamma': [1, 0.1, 0.01, 0.001]},
                   verbose=2)

### Best parameter

In [49]:
print("Best parameter is {}, with score of {}".format(rgrid.best_params_, rgrid.best_score_))

Best parameter is {'gamma': 0.001, 'C': 10}, with score of 0.9330216247808301


### Confusion Matrix

In [50]:
print("Confusion matrix:\n{}".format(confusion_matrix(y_pred, y_test)))

Confusion matrix:
[[ 44   3]
 [  7 141]]


### Accuracy Score

In [51]:
print("Accuracy Score: {}".format(accuracy_score(y_pred, y_test)))

Accuracy Score: 0.9487179487179487


### Classification report

In [52]:
print("Classification report:\n{}".format(classification_report(y_pred, y_test)))

Classification report:
              precision    recall  f1-score   support

           0       0.86      0.94      0.90        47
           1       0.98      0.95      0.97       148

    accuracy                           0.95       195
   macro avg       0.92      0.94      0.93       195
weighted avg       0.95      0.95      0.95       195



---

---